### ISSUE TITLE
Add Lisk Foundation

### ISSUE THREAD

**Issue by Aphelion-dev** [nvk/bitcointreasuries.NET#126]
- [ ] Name: Lisk Foundation
- [ ] Exchange: N/A. private foundation based in Switzerland
Here's switzerlands commercial registry:
Link: https://zg.chregister.ch/cr-portal/auszug/auszug.xhtml?uid=CHE-476.165.977#
Link: https://www.zefix.ch/de/search/entity/list/firm/1284928?name=lisk%2520stiftung&searchType=exact
- [ ] https://lisk.io/
- [ ] Bitcoin Basis price when they did their ICO in 2016: 960,000 USD
- [ ] Market Cap: Total assets under management: 113,000,000 USD
- [ ] Total BTC: 2400 BTC
- [ ] https://lisk.io/blog/foundation/financial-update-december-2020

More information and sources:

Private Company
Name: Lisk Foundation

Commercial registry:
Link: https://zg.chregister.ch/cr-portal/auszug/auszug.xhtml?uid=CHE-476.165.977#
Link: https://www.zefix.ch/de/search/entity/list/firm/1284928?name=lisk%2520stiftung&searchType=exact

Lisk Foundation on crunchbase
Link: https://www.crunchbase.com/organization/lisk

Official website:
Link: https://lisk.io/

Latest financial report:
Link: https://lisk.io/blog/foundation/financial-update-december-2020

Total BTC held:
2400 BTC
Source: https://lisk.io/blog/foundation/financial-update-december-2020
Link to their wallet: https://www.blockchain.com/btc/address/3MCh3xEt733gu4pCMKSHupSJG9raBADMtS

Basis Price:
960,000 USD
Source: https://lisk.io/blog/announcement/lisk-ico-statistics

Total assets under management:
113,000,000 USD
Source: https://lisk.io/blog/foundation/financial-update-december-2020

Thank you for your work!

**Comment by nvk** [comment]
This is a AUM type product right?

**Comment by Aphelion-dev** [comment]
What's your definition of a AUM type product?

The Lisk Foundation is basically the same as the Tezos foundation listed under private companies.
It's neither publicly traded nor ETF like. So it should definitely fall into that category.

**Comment by nvk** [comment]
Do they have a public audit?

**Comment by Aphelion-dev** [comment]
They don't as far as i know.
However they are a registered company in switzerland so they can't just lie about their holdings without legal consequences.
Also their BTC address is public 3MCh3xEt733gu4pCMKSHupSJG9raBADMtS

I corrected the balance in the issue as I wrote 2100 instead of 2400

**Comment by Aphelion-dev** [comment]
Added newest financial report

**Comment by nvk** [comment]
Come add it on the new site bitcointreasuries.net/login
