### ISSUE TITLE
Add Blockfi Bitcoin Trust

### ISSUE THREAD

**Issue by Empact** [nvk/bitcointreasuries.NET#173]
- [x] Name: Blockfi Bitcoin Trust
- [x] Exchange: Not applicable, from website: "There is currently no secondary market for the shares and no there is no guarantee that a secondary market will develop."
- [x] https://www.blockfitrust.com/
- [ ] Bitcoin Purchase Basis price: $XXX USD
- [x] Market Cap: $100,738,323.20 USD
- [x] Total BTC: 1,950.1853 BTC[1]
- [ ] Direct link to latest financial report

Some press:
https://www.prnewswire.com/news-releases/blockfi-launches-the-blockfi-bitcoin-trust-301224712.html
https://finance.yahoo.com/news/blockfi-bitcoin-trust-takes-aim-171226519.html

[1] Number of Bitcoins derived from the current site info: (Bitcoin Holdings) / (Bitcoin Index Price) = (100,738,323.20) / $51,655.77.
Note this is inexact as Bitcoin Holdings carries the following note: "The aggregate value, expressed in U.S. dollars, of the Trust's assets (other than U.S. dollars or other fiat currency), less its liabilities (which include estimated accrued but unpaid fees and expenses)."

Note: Numbers are updated regularly - the above was updated 2021-03-08

**Comment by nvk** [comment]
well, that didn’t last!

Come add it on the new site bitcointreasuries.net/login
