### ISSUE TITLE
Need details on Galaxy ETF TSX:BTCG

### ISSUE THREAD

**Issue by nvk** [nvk/bitcointreasuries.NET#205]
- [ ] Name: Coin Citadel OTC
- [ ] Exchange: symbol (NASDA:SQ) or wherever I can find it
- [ ] Link to google finance or wherever I can find it
- [ ] Bitcoin Purchase Basis price: $XXX USD
- [ ] Market Cap: $XXX USD
- [ ] Total BTC: XXX BTC
- [ ] Direct link to latest financial report

**Please review existing <a href="https://github.com/nvk/bitcointreasuries.org/issues?q=is%3Aissue+is%3Aclosed">closed</a> and open issues before creating a new submission, don't submit just an article without any other information.**

**Comment by FracturedWinter** [comment]
BTCG is merging into BTCX
https://www.businesswire.com/news/home/20210309005349/en/CI-Galaxy-Bitcoin-ETF-Begins-Trading-on-the-TSX-with-World%E2%80%99s-Lowest-Management-Fee-of-any-Bitcoin-ETF

CI's website for BTCX:
https://ci.com/en/investment-solutions/bitcoin

Current stats about BTCX:
https://www.firstasset.com/solutions/overview/?fund=CI+Galaxy+Bitcoin+ETF+%28US%24+Series%29&utm_medium=referral&utm_source=gam_featurepage&utm_campaign=bitcoinetf

**Comment by nvk** [comment]
Is the merger done?

**Comment by FracturedWinter** [comment]
No. There will be a meeting on April 26, 2021 to formally approve the merger. It's then estimated to occur around May 7, 2021. 

Letter documenting details above dated March 15, 2021:
https://www.sedar.com/GetFile.do?lang=EN&docClass=23&issuerNo=00050801&issuerType=03&projectNo=03187285&docId=4910146

All recent regulatory filings for CI Galaxy Fund:
https://www.sedar.com/DisplayCompanyDocuments.do?lang=EN&issuerNo=00050801

**Comment by FracturedWinter** [comment]
The merger was finalized, leaving BTCX as the remaining entity.
https://www.sedar.com/GetFile.do?lang=EN&docClass=13&issuerNo=00050801&issuerType=03&projectNo=03221671&docId=4961114

As of June 11, 2021, the ETF appears to hold approximately 3,237 BTC. 

Calculation: 16,855,314 units outstanding / 5,205.86 units per BTC = 3,237.76

Source of data:
https://www.firstasset.com/solutions/overview/?fund=CI+Galaxy+Bitcoin+ETF+%28US%24+Series%29&utm_medium=referral&utm_source=gam_featurepage&utm_campaign=bitcoinetf

**Comment by nvk** [comment]
Come add it on the new site bitcointreasuries.net/login
