### ISSUE TITLE
KiwiSaver HODL, but can't find info.

### ISSUE THREAD

**Issue by nvk** [nvk/bitcointreasuries.NET#221]
https://twitter.com/woonomic/status/1375313518367404032?s=20

**Comment by tristanhcole** [comment]
This is the [original article from a local NZ outlet, Stuff](https://www.stuff.co.nz/business/124637257/investment-or-speculation-kiwisaver-fund-enters-the-bitcoin-era), that was then cited in [CoinDesk](https://www.coindesk.com/new-zealand-wealth-management-firm-bitcoin).

> “We bought in in October at US$10,000 (NZ$14,360). It was US$62,000 at the weekend, and it’s back at US$55,000 today,” Grigor said.

Looking at their [website](https://www.nzfunds.co.nz/InvestmentSolutions/kiwisaver/) filings, they have a Securities Listing doc:
https://www.nzfunds.co.nz/Assets/Documents/kiwisaver/security-listings/security-listings_KS.pdf

**KiwiSaver Inflation Strategy**
Cryptocurrency future exposure - 5.6% - $5,250,089

**KiwiSaver Growth Strategy**
Cryptocurrency future exposure - 4.8% - $21,644,668
Galaxy Inst Bitcoin Fund - 6.5% - $28,876,272

Total exposure: $55,771,029 

It's unclear exactly what currency, but I'd assume New Zealand Dollars

**Comment by nvk** [comment]
Come add it on the new site bitcointreasuries.net/login
