### ISSUE TITLE
CelsiusNetwork Owns more than 82,000 BTC 

### ISSUE THREAD

**Issue by danzee1** [nvk/bitcointreasuries.NET#226]
In an interview CEO of CelsiusNetwork disclosed that they have more than 82,000 BTC .. Here is the official tweet from celcius

https://twitter.com/CelsiusNetwork/status/1377316724433842180

It needs to be investigated for data as We don't know at which price they acquired etc.

**Comment by nvk** [comment]
Well, that didn’t last!

Come add it on the new site bitcointreasuries.net/login
