### ISSUE TITLE
MassMutual 100M in BTC

### ISSUE THREAD

**Issue by rtknapp** [nvk/bitcointreasuries.NET#228]
- [ ] Name: Massachusetts Mutual Life Insurance Co. 
- [ ] Exchange: symbol (NASDA:SQ) MEFZX?
- [ ] Link to google finance or wherever I can find it: https://www.bloomberg.com/news/articles/2020-12-10/169-year-old-insurer-massmutual-invests-100-million-in-bitcoin
- [ ] Bitcoin Purchase Basis price: $~18K USD ?
- [ ] Market Cap: $ ?
- [ ] Total BTC: ? -  $100M USD 
- [ ] Direct link to latest financial report ?

**Please review existing <a href="https://github.com/nvk/bitcointreasuries.org/issues?q=is%3Aissue+is%3Aclosed">closed</a> and open issues before creating a new submission, don't submit just an article without any other information.**

**Comment by earonesty** [comment]
I feel like this is one of the more important entries can you mention why it is marketing complete and I'll finish filling it out.

**Comment by nvk** [comment]
We don't know the basis cost to calculate the amt of btc purchased.

**Comment by earonesty** [comment]
maybe there should be a way of just putting a question mark there?  it's a broadly confirmed purchase.   i did try to contact mass m btw.  no reply.

**Comment by nvk** [comment]
Come add it on the new site bitcointreasuries.net/login
