### ISSUE TITLE
Add mercado libre

### ISSUE THREAD

**Issue by nvk** [nvk/bitcointreasuries.NET#263]
$7.8 million in bitcoin
Can't find the exchange rate

https://www.sec.gov/edgar/search/#/q=bitcoin&dateRange=custom&entityName=MERCADOLIBRE&startdt=2021-05-05&enddt=2021-05-05

**Comment by SantiSabater** [comment]
Hey there,
An argentinian, the exchange rate has not been confirmed, we will only know about that once the quarterly reports are disclosed by the company to NASDAQ by the end of Q2. 

Until then it might be a good idea to introduce the Bitcoin price at the time of the announcement.

**Comment by nvk** [comment]
Rather wait for real numbers.

**Comment by nvk** [comment]
Come add it on the new site bitcointreasuries.net/login
