### ISSUE TITLE
Globant buy

### ISSUE THREAD

**Issue by davidbil** [nvk/bitcointreasuries.NET#273]
Globant S.A.
NYSE: GLOB
https://www.google.com/finance/quote/GLOB:NYSE
500k @ January
8.60B USD
10-20BTC
https://www.sec.gov/Archives/edgar/data/1557860/000110465921071235/tm2116803d1_ex99-1.htm

**Please review existing <a href="https://github.com/nvk/bitcointreasuries.org/issues?q=is%3Aissue+is%3Aclosed">closed</a> and open issues before creating a new submission, don't submit just an article without any other information.**

**Comment by nvk** [comment]
we need the actual btc amt

**Comment by nvk** [comment]
added
