### ISSUE TITLE
Could you add our fund "Incrementum Digital & Physical Gold Fund" to bitcointreasuries.net?

### ISSUE THREAD

**Issue by HaraldSteinbichler** [nvk/bitcointreasuries.NET#286]
We hold 197,7 Bitcoins as of December 31, 2020 - please find the audited annual report enclosed (see page 12)
Thank you
Harald
[https://axessum.com/wp-content/uploads/Annual-Report-2020-Incrementum-Digital-Physical-Gold-Fund.pdf](url)

**Comment by nvk** [comment]
Are you a listed company?

**Comment by HaraldSteinbichler** [comment]
we are a registered investment fund, supervised by the Financial Market Authority of Liechtenstein.
The fund name is Incrementum Digital & Physical Gold Fund - please have a look at www.incrementum.li/en or https://lafv.li/ENG/Home/Dash
Thank you for your reply
Harald

**Comment by nvk** [comment]
Ok, could you use the template to help me fill in all the items?


ℝ.
(mobile)

**Comment by HaraldSteinbichler** [comment]
sure, can you send me the link of the template?

**Comment by nvk** [comment]
https://docs.google.com/spreadsheets/d/1TqL5qW5rLeEDBhOQk3RwtaJbHA8ExkfsAjJQ4lzCLA8/edit#gid=0

**Comment by HaraldSteinbichler** [comment]
done

**Comment by nvk** [comment]
added
