### ISSUE TITLE
HASH11- Hashdex Nasdaq Crypto Index Fundo de Indice (ETF)

### ISSUE THREAD

**Issue by hashdex** [nvk/bitcointreasuries.NET#290]
- [ ] Name: Hashdex Nasdaq Crypto Index Fundo de Indice
- [ ] Exchange: BVMF: HASH11
- [ ] Link to google finance  https://g.co/finance/HASH11:BVMF
- [ ] Bitcoin Purchase Basis price: $48,180.20 USD
- [ ] Market Cap: $351.7M USD
- [ ] Total BTC: 6014.630342 BTC
% of BTC: Dynamic according to NCI: https://www.nasdaq.com/Crypto-Index

**Please review existing <a href="https://github.com/nvk/bitcointreasuries.org/issues?q=is%3Aissue+is%3Aclosed">closed</a> and open issues before creating a new submission, don't submit just an article without any other information.**

**Comment by nvk** [comment]
What is this, a AUM ETF/ETC like product?

**Comment by nvk** [comment]
added.
