### ISSUE TITLE
HIVE Blockchain update 875BTC Hodl

### ISSUE THREAD

**Issue by iwanttobethebee** [nvk/bitcointreasuries.NET#295]
Hive Blockchain is a Bitcoin miner and recently posted their updated HODL which is currently 875BTC compared to 320that appears on your website.

![Screenshot_20210822-120317](https://user-images.githubusercontent.com/30014413/130362016-57e90d3a-5870-4ea9-9948-b6c7f9200262.png)

**Comment by nvk** [comment]
updated
