### ISSUE TITLE
MSTR update + broken link 

### ISSUE THREAD

**Issue by bitpaint** [nvk/bitcointreasuries.NET#296]
MicroStrategy has purchased an additional 3,907 bitcoins for ~$177 million in cash at an average price of ~$45,294 per #bitcoin.

As of 8/23/21 they own ~108,992 bitcoins acquired for ~$2.918 billion at an average price of ~$26,769 per bitcoin.  
$MSTR
[Link to 8-K form](
https://www.microstrategy.com/content/dam/website-assets/collateral/financial-documents/financial-document-archive/form-8-k_08-24-2021.pdf)

Also the link for "Purchases/Filings" of MicroStrategy seems to go to Ruffer... 
( https://otp.tools.investis.com/clients/uk/ruffer/rns/regulatory-story.aspx?cid=2529&newsid=1436490 ) 

![image](https://user-images.githubusercontent.com/67663265/130647594-0a6a0053-94da-471e-b00c-13d009a6e736.png)

**Comment by nvk** [comment]
udpated. tyhx!
