### ISSUE TITLE
Coin Citadel (OTC - CCTL)

### ISSUE THREAD

**Issue by coincitadel** [nvk/bitcointreasuries.NET#297]
- [ ] Name: Coin Citadel OTC
- [ ] Exchange: symbol (NASDA:SQ) or wherever I can find it
- [ ] Link to google finance or wherever I can find it
- [ ] Bitcoin Purchase Basis price: $XXX USD
- [ ] Market Cap: $XXX USD
- [ ] Total BTC: 4 BTC
- [ ] Direct link to latest financial report - 2020 year end - (https://sec.report/otc/financial-report/276666)
- [ ] Coin Citadel treasury of 576 Bitcoin cannot be verified as private keys and or wallet was lost in transition from old CEO circa 2019. Financials have been updated since 2020 year end and Bitcoin buy from 2014 is no longer listed . Please remove until treasury can be verified

**Please review existing <a href="https://github.com/nvk/bitcointreasuries.org/issues?q=is%3Aissue+is%3Aclosed">closed</a> and open issues before creating a new submission, don't submit just an article without any other information.**

**Comment by nvk** [comment]
updated.
