### ISSUE TITLE
Hive HODL update from 875BTC to 1030BTC(155BTC difference)

### ISSUE THREAD

**Issue by iwanttobethebee** [nvk/bitcointreasuries.NET#301]
- [ ] Name: Hive Blockchain
- [ ] Exchange: symbol (NASDA:HIVE) 
- [ ] https://twitter.com/hiveblockchain/status/1435621455660728326
- [ ] Bitcoin Purchase Basis price: they are a miner
- [ ] Market Cap: $1.064B USD
- [ ] Total BTC: 1030 BTC
- [ ] Report coming next week, update done to their email updates and twitter

![hivebtchodl](https://user-images.githubusercontent.com/30014413/133857919-81a7e4d2-3778-4549-abdf-322549129746.JPG)

**Comment by nvk** [comment]
Do we know the basis cost?

**Comment by iwanttobethebee** [comment]
No

**Comment by iwanttobethebee** [comment]
> Do we know the basis cost?

There's no basis cost because they mined the Bitcoin, On their latest quarter earnings they reported margins of 83% so the cost of mining could be 45*(100%-83%) so you could, in theory, put 7.65K  but, the way they mine is not direct. They mine ETH, ETH classic and Bitcoin. Lately, it has been more profitable to mine ETH than BTC so the real cost of mining must be higher.

**Comment by nvk** [comment]
updated. thx
