### ISSUE TITLE
QR Asset

### ISSUE THREAD

**Issue by frankfarias** [nvk/bitcointreasuries.NET#306]
- [ ] Name: ETF QR Asset
- [ ] Exchange: IBOV:QBTC11
- [ ] https://qrasset.com.br/qbtc11/
- [ ] Bitcoin Purchase Basis price: $XXX USD
- [ ] Market Cap: $38,181,818.18 USD
- [ ] Total BTC: 661 BTC
- [ ] https://qrasset.com.br/qbtc11/#documentos

**Please review existing <a href="https://github.com/nvk/bitcointreasuries.org/issues?q=is%3Aissue+is%3Aclosed">closed</a> and open issues before creating a new submission, don't submit just an article without any other information.**

**Comment by nvk** [comment]
thx, added
