### ISSUE TITLE
On the webpage there is an `L` missing in the name of LQwD

### ISSUE THREAD

**Issue by 0xfff** [nvk/bitcointreasuries.NET#310]
on the webpage there is an `L` missing in the name
<img width="1051" alt="bitcoint net" src="https://user-images.githubusercontent.com/4933679/122469027-4fae2900-cf71-11eb-955c-84398f3b0292.png">

_Originally posted by @0xfff in https://github.com/nvk/bitcointreasuries.NET/issues/285#issuecomment-863548598_

**Comment by 0xfff** [comment]
also LQwD has now 133 BTC [[link](https://ca.finance.yahoo.com/news/lqwd-announces-acquisition-additional-bitcoins-130000883.html)]

**Comment by nvk** [comment]
thx, fixed!

**Comment by 0xfff** [comment]
thanks, i dont think the BTC amount got updated
139 BTC now
https://lqwdfintech.com/news/2021/lqwd-announces-strategic-agreement-with-leading-lightning-network-service-provider-and-additional-acquisition-of-bitcoins/
5th paragraph
