### ISSUE TITLE
$RIOT Updated Bitcoin Holdings (2021.11.03)

### ISSUE THREAD

**Issue by Paanta** [nvk/bitcointreasuries.NET#311]
-  Name: Riot Blockchain
-  Exchange: (NASDA:RIOT)
-  https://www.nasdaq.com/press-release/riot-blockchain-announces-october-production-and-operations-updates-2021-11-03
- [x] Total BTC: "As of October 31, 2021, Riot held approximately 3,995 BTC, all produced by the Company’s self-mining operations."

**Comment by nvk** [comment]
Do we have a basis cost?

**Comment by Paanta** [comment]
They mined it, so no, it would be whatever their blended rate of electricity and CapEx for mining infrastructure is.
