### ISSUE TITLE
MicroStrategy update

### ISSUE THREAD

**Issue by Kapot** [nvk/bitcointreasuries.NET#314]
MicroStrategy has purchased an additional 7,002 bitcoins for ~$414.4 million in cash at an average price of ~$59,187 per #bitcoin. As of 11/29/21 we #hodl ~121,044 bitcoins acquired for ~$3.57 billion at an average price of ~$29,534 per bitcoin. $MSTR

https://twitter.com/saylor/status/1465305537210458115

**Comment by Kapot** [comment]
Sorry not a new entry but cant update that on mobile.

**Comment by nvk** [comment]
Thanks!

**Comment by Kapot** [comment]
Link to latest filing btw (it's not updated yet)

https://www.microstrategy.com/content/dam/website-assets/collateral/financial-documents/financial-document-archive/form-8-k_11-29-2021.pdf

**Comment by nvk** [comment]
updated
