### ISSUE TITLE
Update Square, Inc. to Block, Inc. in company name column

### ISSUE THREAD

**Issue by jeffthibault** [nvk/bitcointreasuries.NET#317]
Square, Inc. has officially changed its company name to Block, Inc.

https://investors.block.xyz/news/news-details/2021/Square-Inc.-Changes-Name-to-Block/default.aspx

**Comment by nvk** [comment]
I'm waiting for them to drop the name everywhere, they are still running the old brand that everyone knows

**Comment by nvk** [comment]
They seem to be keeping both names.
