### ISSUE TITLE
Fidelity Advantage Bitcoin ETF

### ISSUE THREAD

**Issue by FullTimeBitcoin** [nvk/bitcointreasuries.NET#320]
- [ ] Name: Fidelity Advantage Bitcoin ETF
- [ ] Exchange: Toronto Stock Exchange (FBTC, FBTC.U)
- [ ] Link: https://www.fidelity.ca/fidca/en/products/fbtc
- [ ] Bitcoin Purchase Basis price: $XXX USD INCOMPLETE (may be able to calculate this based on starting NAV, but presumably they’ve had new money enter the fund so unlikely)
- [ ] Market Cap: $20,600,000 USD
- [ ] Total BTC: 390.1315 BTC
- [ ] Direct link to latest financial report (Can’t find it)
- [ ] 

(Apologies if this is all wrong, never used GitHub before but I’m on BitcoinTreasuries every day!)

**Please review existing <a href="https://github.com/nvk/bitcointreasuries.org/issues?q=is%3Aissue+is%3Aclosed">closed</a> and open issues before creating a new submission, don't submit just an article without any other information.**

**Comment by nvk** [comment]
added. thx!
