### ISSUE TITLE
Hive update HODL (2,766 BTC difference) from 1,266 to 4,032

### ISSUE THREAD

**Issue by iwanttobethebee** [nvk/bitcointreasuries.NET#323]
Hive has updated their BTC holdings to 4,032 link( https://finance.yahoo.com/news/retransmission-hive-blockchain-updates-total-110000129.html )
![image](https://user-images.githubusercontent.com/30014413/151602783-a1487c6f-abe0-47f1-9b14-9bba8be9078a.png)

**Comment by nvk** [comment]
Thx. Updated
