### ISSUE TITLE
Hashdex Nasdaq Bitcoin ETF

### ISSUE THREAD

**Issue by hashdex** [nvk/bitcointreasuries.NET#324]
- [ ] Name: Hashdex Nasdaq Bitcoin ETF
- [ ] Exchange: symbol (NASDA:SQ)
 Class A: ISIN - KYG4405S1122 
Class B: ISIN - KYG4405S1049  (BSX Ticker: HBTC.BH)
Class C: ISIN - KYG4405S1205
- [ ] Link to google finance or wherever I can find it
Bloomberg: HBTC BH Equity Go
Class B: ISIN - KYG4405S1049

- [ ] Bitcoin Purchase Basis price: Bitcoin Price as of 31.01.2022 $ 38,463.2867000 USD
- [ ] Market Cap: $27,618,192.17 USD (31.01.2022)
- [ ] Total BTC:718,95362187 BTC (31.01.2022)
- [ ] Direct link to latest financial report: https://hashdex.slack.com/files/U029Y6HQFDG/F0312SLB2CU/12-31-21_fact_sheet_hnb_etf.pdf

**Please review existing <a href="https://github.com/nvk/bitcointreasuries.org/issues?q=is%3Aissue+is%3Aclosed">closed</a> and open issues before creating a new submission, don't submit just an article without any other information.**

**Comment by nvk** [comment]
SQ => Square

**Comment by hashdexer** [comment]
Name: Hashdex Bitcoin ETF HBTC1 = 137.368 BTC
Exchange: Brazilian B3 ( BITH11)
Link: https://www.hashdex.com/etfs/bith11/cesta
HNBTC : Hashdex Bitcoin fund = 1363.81 BTC
Hashdex NCI ETF = 7678.08 BTC
