### ISSUE TITLE
Change Fortress Blockchain to Cathedra

### ISSUE THREAD

**Issue by jeffthibault** [nvk/bitcointreasuries.NET#326]
Company Name: Fortress Blockchain -> Cathedra Bitcoin Inc.
Symbol: TSXV:FORT -> TSXV:CBIT

https://www.cathedra.com/news/news/fortress-technologies-rebrands-to-cathedra-bitcoin-inc

**Comment by nvk** [comment]
updated.

**Comment by jeffthibault** [comment]
Company name did not update.

<img width="1006" alt="screenshot" src="https://user-images.githubusercontent.com/30011264/159940980-77f4cea6-0cc2-4547-898b-70a6e663f104.png">

**Comment by nvk** [comment]
reload in a few sec

**Comment by jeffthibault** [comment]
I see it now 👍
