### ISSUE TITLE
update Hut 8 #BTC March 2022

### ISSUE THREAD

**Issue by jzaluski** [nvk/bitcointreasuries.NET#328]
- [ ] Name: Hut 8 Mining
- [ ] Exchange: (NASDA:HUT)
- [ ] Total BTC: 6,460 BTC as of March 31, 2022

[press release](https://www.newswire.ca/news-releases/hut-8-mining-monthly-production-update-for-march-2022-882908784.htm)l

**Comment by nvk** [comment]
updated
