### ISSUE TITLE
US Silk Road

### ISSUE THREAD

**Issue by cmdenny** [nvk/bitcointreasuries.NET#329]
Silk Road founder Ross Ulbricht agrees to use $3 billion in stolen BTC to pay debt to US government

https://www.theblockcrypto.com/linked/143129/silk-road-founder-ross-ulbricht-agrees-to-use-3-billion-in-stolen-btc-to-pay-debt-to-us-government

69,370 BTC 
$2,758,935,081

**Comment by nvk** [comment]
Come keep up to date  on the new site bitcointreasuries.net/login
