### ISSUE TITLE
Angel Studios, Inc.

### ISSUE THREAD

**Issue by holzapfelbaum** [nvk/bitcointreasuries.NET#331]
- [ ] Name: Angel Studios, Inc.
- [ ] Exchange: n/a (private company)
- [ ] https://www.crunchbase.com/organization/angel-studios/company_financials
- [ ] Bitcoin Purchase Basis price: $62,026.08 USD [close price according to Yahoo Finance for 10/18/2021] (total purchase was $10,649,895)
- [ ] Market Cap: $XXX USD (unknown)
- [ ] Total BTC: 171.70027511 BTC (if purchased at close price stated above, still looking for actual exchange rates)
- [ ] Direct link to latest financial report: https://www.sec.gov/Archives/edgar/data/0001671941/000165495422005690/angel_1k.htm

**Please review existing <a href="https://github.com/nvk/bitcointreasuries.org/issues?q=is%3Aissue+is%3Aclosed">closed</a> and open issues before creating a new submission, don't submit just an article without any other information.**

**Comment by holzapfelbaum** [comment]
Wasn't sure where to go to try to confirm purchases. I could potentially reach out to their CFO and COO, but not sure if they'll be open to it.

I'll try it anyway!

**Comment by nvk** [comment]
Come add it on the new site bitcointreasuries.net/login
