### ISSUE TITLE
HashDEX ETF bitcoin update

### ISSUE THREAD

**Issue by hashdexer** [nvk/bitcointreasuries.NET#333]
- Name: Hashdex Bitcoin ETF HBTC1 = 137.368 BTC
 Exchange: Brazilian B3 ( BITH11)
 Link: https://www.hashdex.com/etfs/bith11/cesta
 HNBTC : Hashdex Bitcoin fund = 1363.81 BTC
Hashdex NCI ETF = 7678.08 BTC

 Total BTC: 9179.26 BTC

(Apologies if this is all wrong, never used GitHub before but I’m on BitcoinTreasuries every day!)

**Comment by hashdexer** [comment]
Any Updated pls?

**Comment by nvk** [comment]
Is the trading ticker on Google finance?

**Comment by hashdexer** [comment]
ticker pls - all 5 of them showing only the BTC exposure

`NEW One is HASH SW

On 10 Jun 2022, at 21:00, nvk ***@***.***> wrote:


Is the trading ticker on Google finance?

**Comment by nvk** [comment]
I don’t understand what you are trying to say.

**Comment by hashdexer** [comment]
all our our ETF/ETP are showing just the btc exposure - since we have basket of coint ETF, just want to update you with only the BTC exposure


On 10 Jun 2022, at 21:03, nvk ***@***.***> wrote:


I don’t understand what you are trying to say.

**Comment by hashdexer** [comment]
never saw any update on the amount of BTC we hold in our ETF/ETP, will you still do that ?

**Comment by hashdexer** [comment]
Name: Hashdex Bitcoin ETF HBTC1 = 137.368 BTC
Exchange: Brazilian B3 ( BITH11)
Link: https://www.hashdex.com/etfs/bith11/cesta
HNBTC : Hashdex Bitcoin fund = 1363.81 BTC
Hashdex NCI ETF = 7678.08 BTC
TOTAL AMOUNT FOR THESE ETF is 9179.26 BTC

**Comment by nvk** [comment]
It’s too small for a ETP to be listed, if you promise to keep updating the numbers here for us I will list.

**Comment by hashdexer** [comment]
any update pls, as I still cannot see the number of btc updated for Hashdex, thx

**Comment by hashdexer** [comment]
to recap , Multiple ETF/ETF : HASH11, HASH.SW, BITH11 = Total 9179 BTC

**Comment by nvk** [comment]
Come help update it on the new site bitcointreasuries.net/login
